### ISSUE TITLE
TypeError: init() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by r0hitsharma** [ICTSTUDIO/odoo-extra-addons#14]
For a number of apps cloned today from `10.0` branch (for example Product Stock Location Qty, Product Warehouse Qty), I get the same error:

```
Traceback (most recent call last):
  File "/home/rohit/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/rohit/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/rohit/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/rohit/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/rohit/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/rohit/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/rohit/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/rohit/odoo/addons/web/controllers/main.py", line 886, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/rohit/odoo/addons/web/controllers/main.py", line 874, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/rohit/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/rohit/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/rohit/odoo/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/rohit/odoo/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/rohit/odoo/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/rohit/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/home/rohit/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/rohit/odoo/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/rohit/odoo/odoo/modules/registry.py", line 316, in init_models
    model.init()
TypeError: init() takes exactly 2 arguments (1 given)
```

I'm running a very latest Odoo instance, also cloned from `10.0` Odoo branch.

**Comment by aschenkels-ictstudio** [comment]
Which modules do you want to use in version 10?

Met vriendelijke groet,

André Schenkels

ICTSTUDIO
Middenweg 6
2235 EC Valkenburg Zh
_t +31 6 53250063
_e a.schenkels@ictstudio.eu
_w http://www.ictstudio.eu

**Comment by r0hitsharma** [comment]
I was trying to use the modules Product Stock Location Qty, Product
Warehouse Qty for which I got the error above.

Is it the case that they've not been ported for v10 yet?

Thanks for the help!

**Comment by aschenkels-ictstudio** [comment]
I will port them.

Met vriendelijke groet,

André Schenkels

ICTSTUDIO
Middenweg 6
2235 EC Valkenburg Zh
_t +31 6 53250063
_e a.schenkels@ictstudio.eu
_w http://www.ictstudio.eu

**Comment by aschenkels-ictstudio** [comment]
Product Stock Location for v10 migrated

Met vriendelijke groet,

André Schenkels

ICTSTUDIO
Middenweg 6
2235 EC Valkenburg Zh
_t +31 6 53250063
_e a.schenkels@ictstudio.eu
_w http://www.ictstudio.eu
